# Sidebar navigation

- label: 'Introduction'
  link: '/'
- label: University
  items:
    - label: 'What year are you?'
      link: '/university/what-year-are-you'
    - label: 'Application process'
      link: '/university/application-process'
    - label: 'Increasing the odds'
      link: '/university/increasing-the-odds'
    - label: 'Opportunities for students'
      link: '/university/opportunities-for-students'
    - label: 'Substituting research credits'
      link: '/university/substituting-research-credits'
    - label: 'Work permit'
      link: '/university/work-permit'
- label: For KAIST
  items: 
    - label: 'Data Science Track at KAIST'
      link: '/for-kaist/data-science-track-at-kaist'