# Sidebar navigation

- label: 'Introduction'
  link: '/'
- label: University
  items:
    - label: 'What year are you?'
      link: '/university/what-year-are-you'
    - label: 'Application process'
      link: '/university/application-process'
    - label: 'Opportunities for students'
      link: '/university/opportunities-for-students'
    - label: 'Substituting research credits'
      link: '/university/substituting-research-credits'
    - label: 'Legal Stuff'
      link: '/university/legal-stuff'
